### ISSUE TITLE
Replace woff2_compress command

### ISSUE THREAD

**Issue by miguelsousa** [adobe-fonts/adobe-blank-vf#1]
Replace `woff2_compress` command with,

    $ fonttools ttLib.woff2 compress MyFont.otf

More info at https://github.com/fonttools/fonttools/pull/1639#issuecomment-502195914

**Comment by kenlunde** [comment]
Fixed in [Version 1.003](https://github.com/adobe-fonts/adobe-blank-vf/releases/tag/1.003).
